### PR TITLE
refactor:fix comment

### PR DESCRIPTION
**Pull request by zmdstr**

### CODE REVIEW

**Comment by kezhenxu94** [comment]
@zmdstr I think those comments are meaningless and can be just removed

**Comment by kexianjun** [comment]
So can we close this issue?

**Comment by zmdstr** [comment]
> @zmdstr I think those comments are meaningless and can be just removed

agree

**Comment by zmdstr** [comment]
@kezhenxu94 agree

**Comment by kezhenxu94** [comment]
> @kezhenxu94 agree

@zmdstr Well then, can you just remove the JavaDoc or write some helpful JavaDoc for those classes?

**Pull request closed without merging**
